### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [timthelion/fenfire#2]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by timthelion** [comment]
This project is not active. But feel free to resurrect it again. Or check out https://gingkowriter.com/

I'm currently working on a protocol based version of this here: https://gradesta.com/ but it's not very far along.

**Comment by ghost** [comment]
Hi timthelion.

> his project is not active. But feel free to resurrect it again. Or check out  https://gingkowriter.com/
> I'm currently working on a protocol based version of this here: https://gradesta.com/ but it's not very far along.

thank you for feedback.  So I'm creating a git client that is based on fenfire. please see this:
![image](https://user-images.githubusercontent.com/111701513/215543730-361fbe4b-27a0-4691-bf37-157efd5866d4.png)

*what do you all think of this idea?*

**Comment by timthelion** [comment]
It looks really cool. I started creating a graph based text editor https://hobbs.cz/tg/tg.html and realized that if I'm going to spend all this time creating the graph UI, I want it to be universal. I want to be able to program a graph based git client, a graph based email client, a graph based file browser, a graph based wiki, a graph based debugging interface, a graph based browser favorites organizer, a graph based photo organizer, a graph based music organizer... You get the point. So that's why I started trying to create a universal protocol for serving graphs from a back end to a front end. But it looks like your git tool has a lot of specialized UX around git that probably can't be made universal. So it's an open question what approach will be better :)

**Comment by ghost** [comment]
Hi timthelion.

> It looks really cool. I started creating a graph based text editor https://hobbs.cz/tg/tg.html and realized that if I'm going to spend all this time creating the graph UI, I want it to be universal. I want to be able to program a graph based git client, a graph based email client, a graph based file browser, a graph based wiki, a graph based debugging interface, a graph based browser favorites organizer, a graph based photo organizer, a graph based music organizer... You get the point.

> *a graph based browser favorites organizer*
<img src="https://user-images.githubusercontent.com/111701513/215755162-58fc47a2-13d5-4a48-8f3e-5233f3e9f50a.png" width="580px" alt="image"/>

*this reminds me of an old mosaic browser feature*

> So that's why I started trying to create a universal protocol for serving graphs from a back end to a front end. But it looks like your git tool has a lot of specialized UX around git that probably can't be made universal. So it's an open question what approach will be better :)

So I'm happy with your comment, so please see this: [tylr.fun](https://tylr.fun/) - My general idea is to modify the git client: [guitar](https://github.com/soramimi/Guitar) UI with [tylr](https://github.com/hazelgrove/tylr), hope-js and fenfire. That way, I can manage code from multiple places with a block editor (which works both vertically and horizontally). So... I'm thinking of adding the graph-model to this idea.

*end-concept*
![image](https://user-images.githubusercontent.com/111701513/215678013-a342e2a5-4ecc-4496-b956-44a4bc0f3663.png)

*what do you all think of this idea?*

**Comment by timthelion** [comment]
Is that a mockup or a real interface?

**Comment by ghost** [comment]
Hi timthelion.

> Is that a mockup or a real interface?

mockup - but could be a real interface considering initially that there is a text editor called [tylr](https://tylr.fun/), and there is a git client called [guitar](https://github.com/soramimi/Guitar). In part, this mockup can be a real interface if you consider merging 3 open source projects: fenfire+git client:guitar+tylr.

- *What do you think of this idea?* 
- *Would it be worth having a graph-based git-client and an internal block text editor?*
- *So... I'm thinking of developing this idea(I believe fenfire code can help me to create the graphic model I need for this idea)*

**Comment by timthelion** [comment]
I guess its an interesting idea, not sure about the interopability of the code bases. I think it should be easy to put tyler into guitar because embedding a webui frame is easy. But fenfire is in Haskell and is GTK+Cairo. Not really sure how to mix that kettle of fish ;)

**Comment by ghost** [comment]
Hi timthelion.

> I guess its an interesting idea, not sure about the interopability of the code bases. I think it should be easy to put tyler into guitar because embedding a webui frame is easy. But fenfire is in Haskell and is GTK+Cairo. Not really sure how to mix that kettle of fish ;)

thank you for feedback here again. *I'm going to close this question since... you answered my question, have a great day.*
